kind: pipeline
name: default

steps:
- name: test
  image: python:3.7
  commands:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install -e .[all]
    - ./run-tests.sh

- name: discord-finished
  image: mzaglia/drone-discord-embed
  settings:
    webhook:
      from_secret: discord_webhook
  when:
    status:
      - failure
      - success
