#
# This file is part of Python Module for Cube Builder AWS.
# Copyright (C) 2019-2021 INPE.
#
# Cube Builder AWS is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

[pytest]
addopts = --color=auto --cov=cube_builder_aws/cube_builder_aws --cov-report=term-missing
testpaths = tests