openapi: 3.0.0

info:
  description: Cube generation - API Cube Builder AWS
  version: "0.2.0"
  title: API Cube Builder (AWS)
  contact:
    name: BDC INPE
    email: brazildatacube@dpi.inpe.br
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
    
servers:
  - url: 'https://localhost'
    description: Dev Server

tags:
  - name: "status"
    description: "Status service"
  - name: "cube_builder"
    description: "Cube Builder service"

paths:
  /:
    get:
      tags:
        - "status"
      summary: "Status"
      description: "return status of application"
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  description:
                    type: string
                  message:
                    type: string
                  version:
                    type: string

  /create-grs:
    post:
      tags:
        - "cube_builder"
      summary: "Create GRS"
      description: "Create base GRS (Geographic Reference System)"
      requestBody:
        description: "Initial informations to create GRS"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/request/schemas/GRS"
      responses:
        201:
          description: "Successfully"
          content:
            application/json:
              schema:
                type: string

  /create-raster-size:
    post:
      tags:
        - "cube_builder"
      summary: "Create Raster Size Schema"
      description: "Create base Raster Size"
      requestBody:
        description: "Initial informations to create Raster Size"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/request/schemas/raster_size"
      responses:
        201:
          description: "Successfully"
          content:
            application/json:
              schema:
                $ref: "#/request/schemas/raster_size"

  /raster-size:
    get:
      tags:
        - "cube_builder"
      summary: "Raster Size Schemas"
      description: "list Raster Sizes"
      responses:
        200:
          description: "Successfully"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/response/schemas/Raster_schema"

  /create-temporal-composition:
    post:
      tags:
        - "cube_builder"
      summary: "Create Temporal Composition"
      description: "Create base Temporal Composition"
      requestBody:
        description: "Initial informations to create Temporal Composition"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/request/schemas/temporal_composition"
      responses:
        201:
          description: "Successfully"
          content:
            application/json:
              schema:
                type: string

  /create:
    post:
      tags:
        - "cube_builder"
      summary: "Create Cube"
      description: "Create cube metadata"
      requestBody:
        description: "Initial informations to create Cube"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/request/schemas/cube"
      responses:
        201:
          description: "Successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  cubes: 
                    type: array
                    items:
                      $ref: "#/response/schemas/Cube"

  /start:
    post:
      tags:
        - "cube_builder"
      summary: "Start Cube"
      description: "Start process to generate cube"
      requestBody:
        description: "Initial informations to start Cube"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/request/schemas/start"
      responses:
        200:
          description: "Successfully"
          content:
            application/json:
              schema:
                type: string

request:
  schemas:
    GRS:
      type: object
      required:
        - name
        - description
        - projection
        - meridian
        - degreesx
        - degreesy
        - bbox
      properties:
        name:
          type: string
          description: GRS name
        description:
          type: string
          description: GRS description
        projection:
          type: string
          description: GRS projection (allow => aea, longlat, sinu)
        meridian:
          type: number
          description: central meridian of area
        degreesx:
          type: number
          description: size (X) in degrees of each tile (in degrees)
        degreesy:
          type: number
          description: size (Y) in degrees of each tile (in degrees)
        bbox:
          type: string
          description: bounding box of area (in lnglat) - (W, N, E, S)

    raster_size:
      type: object
      required:
        - grs_schema
        - resolution
        - chunk_size_x
        - chunk_size_y
      properties:
        grs_schema:
          type: string
          description: GRS name
        resolution:
          type: number
          description: Spatial Resolution of cube
        chunk_size_x:
          type: number
          description: chunk size X
        chunk_size_y:
          type: number
          description: chunk size Y

    temporal_composition:
      type: object
      required:
        - temporal_schema
      properties:
        temporal_schema:
          type: string
          description: Schema ['A', 'M', 'S']
        temporal_composite_t:
          type: number
          description: Time/Quantity
        temporal_composite_unit:
          type: string
          description: Unit of quantity

    cube:
      type: object
      required:
        - datacube
        - grs
        - resolution
        - temporal_schema
        - bands_quicklook
        - bands
        - description
        - license
      properties:
        datacube:
          type: string
          description: Cube name (without 'composite_function' in the name)
        grs:
          type: string
          description: name of grs_schema
        resolution:
          type: number
          description: Spatial Resolution of cube
        temporal_schema:
          type: string
          description: name of temporal_schema (e.g. M1month)
        bands_quicklook:
          type: array
          description: list of bands (common name) to composite quicklook (RGB)
          items:
            type: string
        bands:
          type: array
          description: list of bands (common name)
          items:
            type: string
        description:
          type: string
          description: description of cube
        license:
          type: string
          description: license of cube
        oauth_scope:
          type: string
          description: oauth scope (OBT) to cube access

    start:
      type: object
      required:
        - url_stac
        - bucket
        - datacube
        - tiles
        - collections
        - satellite
        - start_date
      properties:
        url_stac:
          type: string
          description: URL STAC with input collection information
        bucket:
          type: string
          description: bucket name - using to save results
        datacube:
          type: string
          description: cube name
        tiles:
          type: array
          description: list of tiles
          items:
            type: string
        collections:
          type: string
          description: collection name
        satellite:
          type: string
          description: satellite name (collection satellite, e.g. LANDSAT, SENTINEL-2, ...)
        start_date:
          type: string
          description: start date to generate cube (format => yyyy-mm-dd)
        last_date:
          type: string
          description: last date to generate cube (format => yyyy-mm-dd)

response:
  schemas:
    Cube:
      type: object
      properties:
        id:
          type: string
        temporal_composition_schema_id:
          type: string
        raster_size_schema_id:
          type: string
        composite_function_schema_id:
          type: string
        grs_schema_id:
          type: string
        description:
          type: string
        radiometric_processing:
          type: string
        geometry_processing:
          type: string
        sensor:
          type: string
        is_cube:
          type: boolean
        license:
          type: string
        bands_quicklook:
          type: string
    Raster_schema:
      type: object
      properties:
        id:
          type: string
        raster_size_x:
          type: number
        raster_size_y:
          type: number
        raster_size_t:
          type: number
        chunk_size_x:
          type: number
        chunk_size_y:
          type: number
        chunk_size_t:
          type: number